# Generated by Django 5.1.5 on 2025-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carinventory_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.FloatField(),
        ),
    ]
