# Generated by Django 5.1.5 on 2025-02-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinventory',
            name='car',
        ),
    ]
